/** User-facing names for model catalog categories returned by the backend. */
export const DOWNLOAD_CATEGORY_LABELS: Record<string, string> = {
  checkpoint: 'Checkpoint',
  sd_singlefile_config: 'Stable Diffusion support config',
  lora: 'LoRA',
  vae: 'VAE',
  controlnet: 'ControlNet',
  preprocessor: 'ControlNet preprocessor',
  upscaler: 'Upscaler',
  esrgan: 'ESRGAN upscaler',
  gfpgan: 'GFPGAN restorer',
  codeformer: 'CodeFormer restorer',
  faceswap: 'Face swap',
  embedding: 'Embedding / Textual inversion',
  hypernetwork: 'Hypernetwork',
  wan_safetensor: 'Wan transformer (safetensors)',
  wan_gguf: 'Wan transformer (GGUF)',
  wan_diffusers: 'Wan Diffusers folder',
  wan_lora: 'Wan LoRA',
  wan_vae: 'Wan VAE',
  wan_text_encoder: 'Wan UMT5-XXL text encoder',
  flux_unet_safetensor: 'Flux UNet / transformer (safetensors)',
  flux_unet_gguf: 'Flux UNet / transformer (GGUF)',
  flux_text_encoder: 'Flux text encoder',
  flux_vae: 'Flux VAE',
  flux_tokenizer: 'Flux tokenizer files',
  flux2_unet_safetensor: 'Flux.2 Klein transformer (safetensors)',
  flux2_unet_gguf: 'Flux.2 Klein transformer (GGUF)',
  flux2_components: 'Flux.2 Klein components',
  flux2_diffusers: 'Flux.2 Klein Diffusers pipeline',
  flux_kontext_diffusers: 'Flux Kontext Diffusers pipeline',
  z_image_unet_safetensor: 'Z-Image transformer (safetensors)',
  z_image_unet_gguf: 'Z-Image transformer (GGUF)',
  z_image_components: 'Z-Image components',
  krea2_unet_safetensor: 'Krea 2 transformer (safetensors)',
  krea2_text_encoder: 'Krea 2 Qwen3-VL text encoder',
  krea2_vae: 'Krea 2 Qwen Image VAE',
  krea2_diffusers: 'Krea 2 Diffusers pipeline',
  anima_unet_safetensor: 'Anima transformer (safetensors)',
  anima_text_encoder: 'Anima Qwen text encoder',
  anima_vae: 'Anima Qwen Image VAE',
  qwen_image_diffusers: 'Qwen Image Diffusers pipeline',
  qwen_image_nunchaku: 'Qwen Image Nunchaku transformer',
  sana_diffusers: 'Sana Diffusers pipeline',
  sana_video_diffusers: 'Sana Video Diffusers pipeline',
  // The catalog category contains both LTX Video 0.9.5 and LTX 2.3 entries.
  // Show each item's version from its title instead of assigning one family
  // version to the entire category.
  ltx_checkpoint: 'LTX video checkpoint (version shown per model)',
  ltx_gguf: 'LTX 2.3 GGUF support asset',
  ltx_upscaler: 'LTX 2.3 upscaler',
  ltx_lora: 'LTX 2.3 LoRA',
  ltx_vae: 'LTX 2.3 video VAE',
  ltx_audio_vae: 'LTX 2.3 audio VAE',
  ltx_text_encoder: 'LTX 2.3 Gemma text encoder',
  ltx_tokenizer: 'LTX 2B T5 tokenizer',
  llm_gguf: 'LLM GGUF',
  llm_safetensor: 'LLM safetensors',
  rife: 'RIFE (frame interpolation)',
  sam: 'SAM (segmentation)',
  other: 'Other (models root)',
}

export function formatDownloadCategoryLabel(category: string): string {
  return DOWNLOAD_CATEGORY_LABELS[category]
    ?? category.replace(/[_-]+/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())
}
