from __future__ import annotations

from aiwf.core.domain.model_download import CatalogEntry

_CN15 = "https://huggingface.co/comfyanonymous/ControlNet-v1-1_fp16_safetensors/resolve/main"
_CN15_FULL_REPO = "lllyasviel/ControlNet-v1-1"
_CN_ANNOTATORS_REPO = "lllyasviel/Annotators"
_CN_SDXL_COLLECTION_REPO = "lllyasviel/sd_control_collection"
_CNXL_UNION_REPO = "xinsir/controlnet-union-sdxl-1.0"
_SAM = "https://dl.fbaipublicfiles.com/segment_anything"
_GDINO = "https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha"
_OPENAI = "https://openaipublic.azureedge.net/clip/models"

# ---------------------------------------------------------------------------
# Quick-start bundle keys (used by Download tab bundle buttons)
# ---------------------------------------------------------------------------
QUICK_START_BUNDLES: dict[str, list[str]] = {
    "video": [
        "wan-gguf-high-q4km",
        "wan-gguf-low-q4km",
        "wan-vae-21",
    ],
    "rife": ["rife-47"],
    "seg": ["sam-vit-b", "gdino-swinb"],
    "faceswap": ["fs-inswapper-fp16"],
    "sd": ["hf-sd15-pruned", "hf-vae-mse"],
    "sdxl": ["hf-sdxl-base", "hf-vae-sdxl", "hf-sdxl-refiner"],
    "sd35": ["hf-sd35-medium"],
    "flux": ["flux-fusion-v2-q4km", "flux-t5-fp16", "flux-clip-l", "flux-ae-vae"],
    "ltx23": ["ltx23-distilled", "ltx23-upscaler-x2", "ltx23-gemma-q4"],
    "controlnet-sd15": [
        "cn15-canny", "cn15-depth", "cn15-openpose",
        "cn15-tile", "cn15-lineart", "cn15-softedge",
    ],
    "controlnet-sdxl": [
        "cnxl-canny", "cnxl-openpose", "cnxl-depth",
    ],
    "embeddings": [
        "emb-easynegative", "emb-badprompt", "emb-negxl",
    ],
}

# ---------------------------------------------------------------------------
# Full catalog
# ---------------------------------------------------------------------------
MODEL_DOWNLOAD_CATALOG: list[CatalogEntry] = [

    # ── Wan I2V ─────────────────────────────────────────────────────────────
    CatalogEntry(
        key="wan-vae-21",
        title="Wan 2.1 VAE",
        category="wan_vae",
        source="huggingface",
        repo_id="Comfy-Org/Wan_2.1_ComfyUI_repackaged",
        filename="split_files/vae/wan_2.1_vae.safetensors",
        size_mb=780,
        notes="Works with Wan 2.1 and 2.2 I2V. Saves to models/VAE/.",
    ),
    CatalogEntry(
        key="wan-gguf-high-q4km",
        title="Wan 2.2 I2V High Noise transformer Q4_K_M",
        category="wan_gguf",
        source="huggingface",
        repo_id="city96/Wan2.2-I2V-A14B-480P-gguf",
        filename="Wan2.2-I2V-A14B-480P-HighNoise-Q4_K_M.gguf",
        size_mb=8600,
        notes="First half of dual-transformer pair. Q4_K_M fits 16 GB VRAM with model offload.",
    ),
    CatalogEntry(
        key="wan-gguf-low-q4km",
        title="Wan 2.2 I2V Low Noise transformer Q4_K_M",
        category="wan_gguf",
        source="huggingface",
        repo_id="city96/Wan2.2-I2V-A14B-480P-gguf",
        filename="Wan2.2-I2V-A14B-480P-LowNoise-Q4_K_M.gguf",
        size_mb=8600,
        notes="Second half of dual-transformer pair. Must match the High Noise model series.",
    ),

    # ── Checkpoints — Hugging Face ───────────────────────────────────────────
    CatalogEntry(
        key="ltx23-distilled",
        title="LTX 2.3 22B distilled checkpoint",
        category="ltx_checkpoint",
        source="huggingface",
        repo_id="Lightricks/LTX-2.3",
        filename="ltx-2.3-22b-distilled-1.1.safetensors",
        notes="Fast LTX 2.3 checkpoint used by AIWF's default LTX worker route.",
    ),
    CatalogEntry(
        key="ltx23-full-dev",
        title="LTX 2.3 22B dev checkpoint",
        category="ltx_checkpoint",
        source="huggingface",
        repo_id="Lightricks/LTX-2.3",
        filename="ltx-2.3-22b-dev.safetensors",
        notes="Full checkpoint for one-stage/prototyping LTX routes. Higher VRAM and slower than distilled.",
    ),
    CatalogEntry(
        key="ltx23-upscaler-x2",
        title="LTX 2.3 spatial upscaler x2",
        category="ltx_upscaler",
        source="huggingface",
        repo_id="Lightricks/LTX-2.3",
        filename="ltx-2.3-spatial-upscaler-x2-1.1.safetensors",
        notes="Required by the current distilled two-stage LTX worker route.",
    ),
    CatalogEntry(
        key="ltx23-distilled-lora",
        title="LTX 2.3 distilled LoRA 384",
        category="ltx_lora",
        source="huggingface",
        repo_id="Lightricks/LTX-2.3",
        filename="ltx-2.3-22b-distilled-lora-384-1.1.safetensors",
        notes="Kept in the LTX LoRA folder so it cannot be mixed with SD, Flux, or Wan LoRAs.",
    ),
    CatalogEntry(
        key="ltx23-gemma-q4",
        title="LTX 2.3 Gemma text encoder QAT Q4",
        category="ltx_text_encoder",
        source="huggingface",
        repo_id="google/gemma-3-12b-it-qat-q4_0-unquantized",
        notes="Repository-shaped Gemma text encoder required by LTX 2.3. May require accepted HF access.",
        snapshot=True,
    ),

    CatalogEntry(
        key="hf-sd15-pruned",
        title="Stable Diffusion 1.5 (fp16 pruned)",
        category="checkpoint",
        source="huggingface",
        repo_id="Comfy-Org/stable-diffusion-v1-5-archive",
        filename="v1-5-pruned-emaonly-fp16.safetensors",
        size_mb=2034,
        notes="Classic SD1.5 base — fp16 pruned single file.",
    ),
    CatalogEntry(
        key="hf-sdxl-base",
        title="Stable Diffusion XL Base 1.0",
        category="checkpoint",
        source="huggingface",
        repo_id="stabilityai/stable-diffusion-xl-base-1.0",
        filename="sd_xl_base_1.0.safetensors",
        size_mb=6617,
        notes="SDXL base — pair with the refiner for best quality.",
    ),
    CatalogEntry(
        key="hf-sdxl-refiner",
        title="Stable Diffusion XL Refiner 1.0",
        category="checkpoint",
        source="huggingface",
        repo_id="stabilityai/stable-diffusion-xl-refiner-1.0",
        filename="sd_xl_refiner_1.0.safetensors",
        size_mb=6082,
        notes="Run SDXL Base at 0.8 denoise then Refiner for final 0.2 for best detail.",
    ),
    CatalogEntry(
        key="hf-sd35-medium",
        title="Stable Diffusion 3.5 Medium (Diffusers folder)",
        category="checkpoint",
        source="huggingface",
        repo_id="stabilityai/stable-diffusion-3.5-medium",
        notes=(
            "SD3.5 MMDiT-X text-to-image model. Gated Stability Community License; "
            "accept the Hugging Face gate and set HF_TOKEN/HUGGINGFACE_TOKEN before downloading."
        ),
        snapshot=True,
    ),
    CatalogEntry(
        key="hf-sd35-large-turbo",
        title="Stable Diffusion 3.5 Large Turbo (Diffusers folder)",
        category="checkpoint",
        source="huggingface",
        repo_id="stabilityai/stable-diffusion-3.5-large-turbo",
        notes=(
            "Fast distilled SD3.5 route. Use about 4-8 steps and CFG 0-1. "
            "Gated Stability Community License; needs accepted HF access."
        ),
        snapshot=True,
    ),
    CatalogEntry(
        key="hf-sd35-large",
        title="Stable Diffusion 3.5 Large (Diffusers folder)",
        category="checkpoint",
        source="huggingface",
        repo_id="stabilityai/stable-diffusion-3.5-large",
        notes=(
            "Full 8B SD3.5 model. Quality route for high VRAM/offload; Medium or Large Turbo "
            "is the practical consumer-GPU starting point. Gated Stability Community License."
        ),
        snapshot=True,
    ),

    # Flux runtime assets - Hugging Face
    CatalogEntry(
        key="flux-dev-q4km",
        title="Flux.1 dev UNet GGUF Q4_K_M",
        category="flux_unet_gguf",
        source="huggingface",
        repo_id="unsloth/FLUX.1-dev-GGUF",
        filename="flux1-dev-Q4_K_M.gguf",
        size_mb=6930,
        notes=(
            "Safe fallback Flux dev quant. Lower VRAM than Q5_K_M, but visibly more compressed. "
            "Use with Flux CLIP-L, a T5 encoder, and ae.safetensors."
        ),
    ),
    CatalogEntry(
        key="flux-dev-q5km",
        title="Flux.1 dev UNet GGUF Q5_K_M",
        category="flux_unet_gguf",
        source="huggingface",
        repo_id="unsloth/FLUX.1-dev-GGUF",
        filename="flux1-dev-Q5_K_M.gguf",
        size_mb=8420,
        notes=(
            "Recommended first target for 16 GB cards when 12 GB inference is the goal and "
            "14 GB is acceptable. Keep Q4_K_M installed as fallback."
        ),
    ),
    CatalogEntry(
        key="flux-dev-q6k",
        title="Flux.1 dev UNet GGUF Q6_K",
        category="flux_unet_gguf",
        source="huggingface",
        repo_id="unsloth/FLUX.1-dev-GGUF",
        filename="flux1-dev-Q6_K.gguf",
        size_mb=9850,
        notes=(
            "Quality experiment for 16 GB cards after Q5_K_M benchmarks cleanly. "
            "Likely needs careful text-encoder quant/offload choices."
        ),
    ),
    CatalogEntry(
        key="flux-t5-q4km",
        title="Flux T5-XXL text encoder GGUF Q4_K_M",
        category="flux_text_encoder",
        source="huggingface",
        repo_id="city96/t5-v1_1-xxl-encoder-gguf",
        filename="t5-v1_1-xxl-encoder-Q4_K_M.gguf",
        size_mb=4760,
        notes=(
            "Quantized T5 route for Flux. This matters as much as the UNet quant for "
            "staying near a 12-14 GB inference budget."
        ),
    ),
    CatalogEntry(
        key="flux-t5-fp16",
        title="Flux T5-XXL text encoder safetensors fp16",
        category="flux_text_encoder",
        source="huggingface",
        repo_id="comfyanonymous/flux_text_encoders",
        filename="t5xxl_fp16.safetensors",
        size_mb=9334,
        notes=(
            "Backend-supported T5-XXL encoder for the current Diffusers Flux route. "
            "Use this with CLIP-L, ae.safetensors, and a Flux transformer."
        ),
    ),
    CatalogEntry(
        key="flux-clip-l",
        title="Flux CLIP-L text encoder",
        category="flux_text_encoder",
        source="huggingface",
        repo_id="comfyanonymous/flux_text_encoders",
        filename="clip_l.safetensors",
        size_mb=246,
        notes="Required CLIP-L encoder for Flux split-model workflows.",
    ),
    CatalogEntry(
        key="flux-ae-vae",
        title="Flux ae.safetensors VAE",
        category="flux_vae",
        source="huggingface",
        repo_id="Comfy-Org/Lumina_Image_2.0_Repackaged",
        filename="split_files/vae/ae.safetensors",
        size_mb=320,
        notes="Flux autoencoder/VAE used by split Flux workflows.",
    ),
    CatalogEntry(
        key="fluxtrait-v10-fp8",
        title="Fluxtrait Flux.1 dev FP8 transformer",
        category="flux_unet_safetensor",
        source="civitai",
        civitai_model_id=2086049,
        civitai_version_id=2360245,
        filename="fluxtraitFLUX2KleinFLUXZ_v10FP8.safetensors",
        size_mb=11346,
        notes=(
            "CivitAI Fluxtrait Flux.1 dev FP8 variant. Use with Flux CLIP-L, T5-XXL, "
            "and ae.safetensors. This is a Flux transformer, not an SD checkpoint."
        ),
    ),
    CatalogEntry(
        key="fluxtrait-v20-q4km",
        title="Fluxtrait Flux.1 dev GGUF Q4_K_M",
        category="flux_unet_gguf",
        source="civitai",
        civitai_model_id=2086049,
        civitai_version_id=2496020,
        filename="fluxtraitFLUX2KleinFLUXZ_v20Q4KM.gguf",
        size_mb=6615,
        notes="CivitAI Fluxtrait Flux.1 dev Q4_K_M GGUF. Lower VRAM fallback for 16 GB cards.",
    ),
    CatalogEntry(
        key="fluxtrait-v20-q5km",
        title="Fluxtrait Flux.1 dev GGUF Q5_K_M",
        category="flux_unet_gguf",
        source="civitai",
        civitai_model_id=2086049,
        civitai_version_id=2496097,
        filename="fluxtraitFLUX2KleinFLUXZ_v20Q5KM.gguf",
        size_mb=8028,
        notes="CivitAI Fluxtrait Flux.1 dev Q5_K_M GGUF. Quality target after Q4_K_M is verified.",
    ),
    CatalogEntry(
        key="flux-fusion-v2-q4km",
        title="Flux Fusion V2 4-step GGUF Q4_K_M",
        category="flux_unet_gguf",
        source="civitai",
        civitai_model_id=630820,
        civitai_version_id=944898,
        filename="fluxFusionV24StepsGGUFNF4_V2GGUFQ4KM.gguf",
        size_mb=6595,
        notes=(
            "CivitAI Flux.1 dev derivative with a working public download. "
            "Fast 4-step Q4_K_M route for first Flux tests on 16 GB cards."
        ),
    ),
    CatalogEntry(
        key="flux-fusion-v2-q5km",
        title="Flux Fusion V2 4-step GGUF Q5_K_M",
        category="flux_unet_gguf",
        source="civitai",
        civitai_model_id=630820,
        civitai_version_id=944753,
        filename="fluxFusionV24StepsGGUFNF4_V2GGUFQ5KM.gguf",
        size_mb=8020,
        notes="CivitAI Flux.1 dev derivative. Q5_K_M quality target after Q4_K_M benchmarks cleanly.",
    ),
    # Checkpoints - CivitAI
    CatalogEntry(
        key="civit-dreamshaper-8",
        title="DreamShaper 8 (SD1.5)",
        category="checkpoint",
        source="civitai",
        civitai_model_id=4384,
        size_mb=2000,
        notes="Versatile SD1.5 checkpoint, great for illustrations and photorealism.",
    ),
    CatalogEntry(
        key="civit-realistic-vision-v6",
        title="Realistic Vision V6.0 B1 (SD1.5)",
        category="checkpoint",
        source="civitai",
        civitai_model_id=4201,
        size_mb=2000,
        notes="Best SD1.5 photorealism checkpoint. VAE baked in.",
    ),
    CatalogEntry(
        key="civit-deliberate-v6",
        title="Deliberate v6 (SD1.5)",
        category="checkpoint",
        source="civitai",
        civitai_model_id=4823,
        size_mb=2000,
        notes="High-detail semi-realistic SD1.5 model.",
    ),
    CatalogEntry(
        key="civit-juggernaut-xl",
        title="Juggernaut XL v9 (SDXL)",
        category="checkpoint",
        source="civitai",
        civitai_model_id=133005,
        size_mb=6500,
        notes="Strong general-purpose SDXL checkpoint. Excellent photorealism.",
    ),
    CatalogEntry(
        key="civit-realvisxl",
        title="RealVisXL V4.0 (SDXL)",
        category="checkpoint",
        source="civitai",
        civitai_model_id=139562,
        size_mb=6500,
        notes="Photoreal SDXL checkpoint, consistent humans.",
    ),
    CatalogEntry(
        key="civit-dreamshaper-xl",
        title="DreamShaper XL v2 (SDXL)",
        category="checkpoint",
        source="civitai",
        civitai_model_id=112902,
        size_mb=6500,
        notes="SDXL version of DreamShaper — versatile, detailed.",
    ),
    CatalogEntry(
        key="civit-pony-diffusion-xl",
        title="Pony Diffusion XL v6 (SDXL)",
        category="checkpoint",
        source="civitai",
        civitai_model_id=257749,
        size_mb=6500,
        notes="Anime/illustration SDXL model with extensive style tags.",
    ),

    # ── LoRAs ────────────────────────────────────────────────────────────────
    CatalogEntry(
        key="civit-lora-add-detail",
        title="Add More Details (SD1.5 LoRA)",
        category="lora",
        source="civitai",
        civitai_model_id=82098,
        notes="Detail enhancer for SD1.5. Weight 0.5–1.0.",
    ),
    CatalogEntry(
        key="civit-lora-detail-xl",
        title="Detail Tweaker XL (SDXL LoRA)",
        category="lora",
        source="civitai",
        civitai_model_id=122359,
        notes="Detail enhancer for SDXL. Weight 0.5–1.0.",
    ),
    CatalogEntry(
        key="hf-lora-hyper-sdxl-8step",
        title="Hyper-SDXL 8-step LoRA (CFG)",
        category="lora",
        source="huggingface",
        repo_id="ByteDance/Hyper-SD",
        filename="Hyper-SDXL-8steps-CFG-lora.safetensors",
        size_mb=751,
        notes="Run SDXL at 8 steps, CFG 5-8. Weight ~0.7.",
    ),
    CatalogEntry(
        key="hf-lora-hyper-sd15-8step",
        title="Hyper-SD1.5 8-step LoRA (CFG)",
        category="lora",
        source="huggingface",
        repo_id="ByteDance/Hyper-SD",
        filename="Hyper-SD15-8steps-CFG-lora.safetensors",
        size_mb=257,
        notes="Run SD1.5 at 8 steps with normal CFG.",
    ),
    CatalogEntry(
        key="hf-lora-lcm-sdxl",
        title="LCM-LoRA SDXL",
        category="lora",
        source="huggingface",
        repo_id="latent-consistency/lcm-lora-sdxl",
        filename="pytorch_lora_weights.safetensors",
        size_mb=376,
        notes="4-8 steps at CFG 1-2 with the LCM sampler.",
    ),
    CatalogEntry(
        key="hf-lora-lcm-sd15",
        title="LCM-LoRA SD1.5",
        category="lora",
        source="huggingface",
        repo_id="latent-consistency/lcm-lora-sdv1-5",
        filename="pytorch_lora_weights.safetensors",
        size_mb=145,
        notes="4-8 steps at CFG 1-2 with the LCM sampler on SD1.5.",
    ),

    # ── Embeddings (Textual Inversion) ───────────────────────────────────────
    CatalogEntry(
        key="emb-easynegative",
        title="EasyNegative (SD1.5 embedding)",
        category="embedding",
        source="civitai",
        civitai_model_id=7808,
        notes=(
            "Add 'EasyNegative' to your negative prompt. "
            "Reduces artifacts, bad anatomy, and low quality outputs."
        ),
    ),
    CatalogEntry(
        key="emb-badprompt",
        title="BadDream + UnrealisticDream (SD1.5)",
        category="embedding",
        source="civitai",
        civitai_model_id=72437,
        notes="Pair with FastNegativeV2 for best results on SD1.5 realistic models.",
    ),
    CatalogEntry(
        key="emb-fastnegv2",
        title="FastNegativeV2 (SD1.5 embedding)",
        category="embedding",
        source="civitai",
        civitai_model_id=71961,
        notes="Lightweight negative embedding for SD1.5. Use weight 0.8 in negatives.",
    ),
    CatalogEntry(
        key="emb-ng-deepneg",
        title="ng_deepnegative_v1_75t (SD1.5)",
        category="embedding",
        source="civitai",
        civitai_model_id=4629,
        notes="Classic deep negative embedding. 'ng_deepnegative_v1_75t' in negative prompt.",
    ),
    CatalogEntry(
        key="emb-negxl",
        title="negativeXL_D (SDXL embedding)",
        category="embedding",
        source="civitai",
        civitai_model_id=118418,
        notes="General negative embedding for SDXL. Add to negative prompt at weight 1.0.",
    ),
    CatalogEntry(
        key="emb-unaesthetic-xl",
        title="unaestheticXL (SDXL embedding)",
        category="embedding",
        source="civitai",
        civitai_model_id=119032,
        notes="Quality-boosting SDXL negative embedding. Pairs well with negativeXL_D.",
    ),

    # ── VAE ──────────────────────────────────────────────────────────────────
    CatalogEntry(
        key="hf-vae-mse",
        title="SD VAE FT MSE Original (SD1.5)",
        category="vae",
        source="huggingface",
        repo_id="stabilityai/sd-vae-ft-mse-original",
        filename="vae-ft-mse-840000-ema-pruned.safetensors",
        size_mb=319,
        notes="Fixes washed-out SD1.5 colors. Not needed if checkpoint has VAE baked in.",
    ),
    CatalogEntry(
        key="hf-vae-sdxl",
        title="SDXL VAE fp16 fix",
        category="vae",
        source="huggingface",
        repo_id="madebyollin/sdxl-vae-fp16-fix",
        filename="sdxl_vae.safetensors",
        size_mb=319,
        notes="Required to run SDXL VAE in fp16 without NaN artifacts.",
    ),

    # ── ControlNet — SD1.5 (v1.1 fp16 safetensors) ──────────────────────────
    CatalogEntry(
        key="cn15-v11-full-suite",
        title="ControlNet v1.1 full suite (SD1.5, .pth + .yaml)",
        category="controlnet",
        source="huggingface",
        repo_id=_CN15_FULL_REPO,
        size_mb=20200,
        notes=(
            "Full original SD1.5 ControlNet-v1.1 folder with paired YAML configs. "
            "Large download; use individual fp16 safetensors below for smaller installs."
        ),
        snapshot=True,
    ),
    CatalogEntry(
        key="cn15-canny",
        title="ControlNet v1.1 Canny (SD1.5)",
        category="controlnet",
        source="direct",
        url=f"{_CN15}/control_v11p_sd15_canny_fp16.safetensors",
        size_mb=689,
        notes="Edge detection control. Preprocessor: CannyDetector.",
    ),
    CatalogEntry(
        key="cn15-depth",
        title="ControlNet v1.1 Depth (SD1.5)",
        category="controlnet",
        source="direct",
        url=f"{_CN15}/control_v11f1p_sd15_depth_fp16.safetensors",
        size_mb=689,
        notes="Depth map control. Preprocessors: MiDaS, ZoeDepth, DPT-Hybrid.",
    ),
    CatalogEntry(
        key="cn15-openpose",
        title="ControlNet v1.1 OpenPose (SD1.5)",
        category="controlnet",
        source="direct",
        url=f"{_CN15}/control_v11p_sd15_openpose_fp16.safetensors",
        size_mb=689,
        notes="Pose skeleton control. Preprocessors: OpenPose, DWPose.",
    ),
    CatalogEntry(
        key="cn15-tile",
        title="ControlNet v1.1 Tile (SD1.5)",
        category="controlnet",
        source="direct",
        url=f"{_CN15}/control_v11f1e_sd15_tile_fp16.safetensors",
        size_mb=689,
        notes="Tiled upscaling control. No preprocessor needed — use original image.",
    ),
    CatalogEntry(
        key="cn15-lineart",
        title="ControlNet v1.1 LineArt (SD1.5)",
        category="controlnet",
        source="direct",
        url=f"{_CN15}/control_v11p_sd15_lineart_fp16.safetensors",
        size_mb=689,
        notes="Anime/realistic line art control. Preprocessors: LineArt, LineArtAnime.",
    ),
    CatalogEntry(
        key="cn15-lineart-anime",
        title="ControlNet v1.1 LineArt Anime (SD1.5)",
        category="controlnet",
        source="direct",
        url=f"{_CN15}/control_v11p_sd15s2_lineart_anime_fp16.safetensors",
        size_mb=689,
        notes="Anime line-art control. Preprocessor: LineArt Anime.",
    ),
    CatalogEntry(
        key="cn15-softedge",
        title="ControlNet v1.1 SoftEdge (SD1.5)",
        category="controlnet",
        source="direct",
        url=f"{_CN15}/control_v11p_sd15_softedge_fp16.safetensors",
        size_mb=689,
        notes="Soft edge detection (HED/PIDI). More flexible than Canny.",
    ),
    CatalogEntry(
        key="cn15-normalbae",
        title="ControlNet v1.1 NormalMap BAE (SD1.5)",
        category="controlnet",
        source="direct",
        url=f"{_CN15}/control_v11p_sd15_normalbae_fp16.safetensors",
        size_mb=689,
        notes="Surface normal map control. Preprocessor: NormalBae.",
    ),
    CatalogEntry(
        key="cn15-scribble",
        title="ControlNet v1.1 Scribble (SD1.5)",
        category="controlnet",
        source="direct",
        url=f"{_CN15}/control_v11p_sd15_scribble_fp16.safetensors",
        size_mb=689,
        notes="Rough sketch/scribble control. Preprocessors: HED Scribble, PidiNet Scribble.",
    ),
    CatalogEntry(
        key="cn15-mlsd",
        title="ControlNet v1.1 MLSD Lines (SD1.5)",
        category="controlnet",
        source="direct",
        url=f"{_CN15}/control_v11p_sd15_mlsd_fp16.safetensors",
        size_mb=689,
        notes="Straight-line (architecture) control. Preprocessor: MLSD.",
    ),
    CatalogEntry(
        key="cn15-seg",
        title="ControlNet v1.1 Segmentation (SD1.5)",
        category="controlnet",
        source="direct",
        url=f"{_CN15}/control_v11p_sd15_seg_fp16.safetensors",
        size_mb=689,
        notes="Semantic segmentation control. Preprocessor: OneFormer/Uniformer.",
    ),
    CatalogEntry(
        key="cn15-inpaint",
        title="ControlNet v1.1 Inpaint (SD1.5)",
        category="controlnet",
        source="direct",
        url=f"{_CN15}/control_v11p_sd15_inpaint_fp16.safetensors",
        size_mb=689,
        notes="Inpainting control — use instead of the inpaint checkpoint for more flexibility.",
    ),
    CatalogEntry(
        key="cn15-shuffle",
        title="ControlNet v1.1 Shuffle (SD1.5)",
        category="controlnet",
        source="direct",
        url=f"{_CN15}/control_v11e_sd15_shuffle_fp16.safetensors",
        size_mb=689,
        notes="Color/composition palette transfer from reference image.",
    ),
    CatalogEntry(
        key="cn15-ip2p",
        title="ControlNet v1.1 IP2P (SD1.5)",
        category="controlnet",
        source="direct",
        url=f"{_CN15}/control_v11e_sd15_ip2p_fp16.safetensors",
        size_mb=689,
        notes="InstructPix2Pix-style image editing control.",
    ),

    # ── ControlNet — SDXL ────────────────────────────────────────────────────
    CatalogEntry(
        key="cnxl-union-full",
        title="ControlNet Union SDXL 1.0 (xinsir, diffusers folder)",
        category="controlnet",
        source="huggingface",
        repo_id=_CNXL_UNION_REPO,
        size_mb=5070,
        notes="Multi-control SDXL diffusers folder. Supports the default union model and ships the ProMax weights.",
        snapshot=True,
    ),
    CatalogEntry(
        key="cnxl-collection-full",
        title="SDXL ControlNet collection (lllyasviel)",
        category="controlnet",
        source="huggingface",
        repo_id=_CN_SDXL_COLLECTION_REPO,
        size_mb=28100,
        notes=(
            "Large SDXL collection with full, mid, and small canny/depth models plus openpose/softedge variants. "
            "AIWF lists supported ControlNetModel files and ignores IP-Adapter/T2I-adapter files in this folder."
        ),
        snapshot=True,
    ),
    CatalogEntry(
        key="cnxl-canny",
        title="ControlNet Canny SDXL (xinsir, diffusers folder)",
        category="controlnet",
        source="huggingface",
        repo_id="xinsir/controlnet-canny-sdxl-1.0",
        size_mb=2494,
        notes="Canny edge control for SDXL. Saves the full Diffusers folder so config and weights stay together.",
        snapshot=True,
    ),
    CatalogEntry(
        key="cnxl-openpose",
        title="ControlNet OpenPose SDXL (xinsir, diffusers folder)",
        category="controlnet",
        source="huggingface",
        repo_id="xinsir/controlnet-openpose-sdxl-1.0",
        size_mb=2494,
        notes="Pose control for SDXL. Saves the full Diffusers folder so config and weights stay together.",
        snapshot=True,
    ),
    CatalogEntry(
        key="cnxl-depth",
        title="ControlNet Depth SDXL (diffusers folder)",
        category="controlnet",
        source="huggingface",
        repo_id="diffusers/controlnet-depth-sdxl-1.0",
        size_mb=2494,
        notes="Depth map control for SDXL. Saves the full Diffusers folder so config and weights stay together.",
        snapshot=True,
    ),
    CatalogEntry(
        key="cnxl-softedge",
        title="ControlNet SoftEdge SDXL (SargeZT, diffusers folder)",
        category="controlnet",
        source="huggingface",
        repo_id="SargeZT/controlnet-sd-xl-1.0-softedge-dexined",
        size_mb=2494,
        notes="Soft edge / DexiNed edge detection for SDXL. Saves the full Diffusers folder so config and weights stay together.",
        snapshot=True,
    ),

    # ── ControlNet Preprocessors ─────────────────────────────────────────────
    CatalogEntry(
        key="pre-annotators-full-suite",
        title="ControlNet Annotators full suite",
        category="preprocessor",
        source="huggingface",
        repo_id=_CN_ANNOTATORS_REPO,
        size_mb=10600,
        notes="Full lllyasviel Annotators folder: depth, pose, HED/PIDI, MLSD, normal, lineart, segmentation, and related weights.",
        snapshot=True,
    ),
    CatalogEntry(
        key="pre-dwpose",
        title="DWPose body+hand+face estimator",
        category="preprocessor",
        source="huggingface",
        repo_id="yzd-v/DWPose",
        filename="dw-ll_ucoco_384.onnx",
        size_mb=280,
        notes=(
            "Best pose preprocessor for ControlNet OpenPose. "
            "Also download dw-ll_ucoco_384.pth for the DW detector."
        ),
    ),
    CatalogEntry(
        key="pre-midas-depth",
        title="MiDaS Depth v2.1 Large",
        category="preprocessor",
        source="direct",
        url="https://github.com/isl-org/MiDaS/releases/download/v2_1/dpt_large_384.pt",
        size_mb=414,
        notes="Classic depth estimator. Faster than ZoeDepth, lower accuracy.",
    ),
    CatalogEntry(
        key="pre-dpt-hybrid",
        title="DPT Hybrid MiDaS depth",
        category="preprocessor",
        source="direct",
        url="https://huggingface.co/lllyasviel/Annotators/resolve/main/dpt_hybrid-midas-501f0c75.pt",
        size_mb=493,
        notes="MiDaS/DPT hybrid depth estimator used by common ControlNet depth preprocessors.",
    ),
    CatalogEntry(
        key="pre-zoe-depth",
        title="ZoeDepth (metric depth estimator)",
        category="preprocessor",
        source="direct",
        url="https://huggingface.co/lllyasviel/Annotators/resolve/main/ZoeD_M12_N.pt",
        size_mb=1440,
        notes="Metric depth estimator — best accuracy for indoor scenes.",
    ),
    CatalogEntry(
        key="pre-openpose-body",
        title="OpenPose body model",
        category="preprocessor",
        source="direct",
        url="https://huggingface.co/lllyasviel/Annotators/resolve/main/body_pose_model.pth",
        size_mb=209,
        notes="Body pose estimator for OpenPose ControlNet preprocessing.",
    ),
    CatalogEntry(
        key="pre-openpose-hand",
        title="OpenPose hand model",
        category="preprocessor",
        source="direct",
        url="https://huggingface.co/lllyasviel/Annotators/resolve/main/hand_pose_model.pth",
        size_mb=147,
        notes="Hand pose estimator for OpenPose ControlNet preprocessing.",
    ),
    CatalogEntry(
        key="pre-openpose-face",
        title="OpenPose face model",
        category="preprocessor",
        source="direct",
        url="https://huggingface.co/lllyasviel/Annotators/resolve/main/facenet.pth",
        size_mb=154,
        notes="Face landmark estimator for OpenPose ControlNet preprocessing.",
    ),
    CatalogEntry(
        key="pre-hed",
        title="HED softedge model",
        category="preprocessor",
        source="direct",
        url="https://huggingface.co/lllyasviel/Annotators/resolve/main/ControlNetHED.pth",
        size_mb=29,
        notes="HED edge detector for softedge and scribble-style preprocessors.",
    ),
    CatalogEntry(
        key="pre-pidinet",
        title="PidiNet edge model",
        category="preprocessor",
        source="direct",
        url="https://huggingface.co/lllyasviel/Annotators/resolve/main/table5_pidinet.pth",
        size_mb=3,
        notes="PidiNet edge detector for softedge/scribble preprocessing.",
    ),
    CatalogEntry(
        key="pre-mlsd",
        title="MLSD line detector",
        category="preprocessor",
        source="direct",
        url="https://huggingface.co/lllyasviel/Annotators/resolve/main/mlsd_large_512_fp32.pth",
        size_mb=6,
        notes="Straight-line detector for architecture and perspective ControlNet maps.",
    ),
    CatalogEntry(
        key="pre-normalbae",
        title="NormalBae surface estimator",
        category="preprocessor",
        source="direct",
        url="https://huggingface.co/lllyasviel/Annotators/resolve/main/scannet.pt",
        size_mb=272,
        notes="Surface normal estimator for ControlNet NormalBae.",
    ),
    CatalogEntry(
        key="pre-oneformer-ade20k",
        title="OneFormer ADE20K segmentation",
        category="preprocessor",
        source="direct",
        url="https://huggingface.co/lllyasviel/Annotators/resolve/main/250_16_swin_l_oneformer_ade20k_160k.pth",
        size_mb=950,
        notes="Semantic segmentation preprocessor model for ControlNet segmentation.",
    ),
    CatalogEntry(
        key="pre-oneformer-coco",
        title="OneFormer COCO segmentation",
        category="preprocessor",
        source="direct",
        url="https://huggingface.co/lllyasviel/Annotators/resolve/main/150_16_swin_l_oneformer_coco_100ep.pth",
        size_mb=950,
        notes="COCO semantic segmentation preprocessor model.",
    ),
    CatalogEntry(
        key="pre-lineart-realistic",
        title="LineArt Realistic preprocessor",
        category="preprocessor",
        source="direct",
        url="https://huggingface.co/lllyasviel/Annotators/resolve/main/sk_model.pth",
        size_mb=158,
        notes="Extracts realistic line art from photos.",
    ),
    CatalogEntry(
        key="pre-lineart-anime",
        title="LineArt Anime preprocessor",
        category="preprocessor",
        source="direct",
        url="https://huggingface.co/lllyasviel/Annotators/resolve/main/netG.pth",
        size_mb=274,
        notes="Extracts anime-style line art.",
    ),
    CatalogEntry(
        key="pre-clip-vit-h",
        title="CLIP ViT-H/14 (OpenAI)",
        category="preprocessor",
        source="direct",
        url=f"{_OPENAI}/a37b88a3b52a98db4f723e4a6bde19e3f03e9e0f/ViT-H-14.pt",
        size_mb=3900,
        notes=(
            "Large CLIP vision encoder. Used by IP-Adapter, BLIP, and interrogators. "
            "Also required by some ControlNet preprocessors."
        ),
    ),
    CatalogEntry(
        key="pre-clip-vit-l",
        title="CLIP ViT-L/14 (OpenAI)",
        category="preprocessor",
        source="direct",
        url=f"{_OPENAI}/b8cca3fd41ae0c99ba7e8951adf17d267cdb84cd/ViT-L-14.pt",
        size_mb=890,
        notes="Standard CLIP encoder used by SD1.5 and SDXL (dual encoder).",
    ),

    # ── Segment / DINO ───────────────────────────────────────────────────────
    CatalogEntry(
        key="sam-vit-b",
        title="SAM ViT-B (375 MB)",
        category="sam",
        source="direct",
        url=f"{_SAM}/sam_vit_b_01ec64.pth",
        size_mb=375,
        notes="Fastest SAM model. Good for most segmentation tasks.",
    ),
    CatalogEntry(
        key="sam-vit-l",
        title="SAM ViT-L (1.2 GB)",
        category="sam",
        source="direct",
        url=f"{_SAM}/sam_vit_l_0b3195.pth",
        size_mb=1250,
        notes="Better accuracy than ViT-B.",
    ),
    CatalogEntry(
        key="sam-vit-h",
        title="SAM ViT-H (2.5 GB)",
        category="sam",
        source="direct",
        url=f"{_SAM}/sam_vit_h_4b8939.pth",
        size_mb=2560,
        notes="Highest accuracy SAM. Requires ~8 GB VRAM for inference.",
    ),
    CatalogEntry(
        key="gdino-swint",
        title="GroundingDINO Swin-T (text-guided seg)",
        category="sam",
        source="direct",
        url=f"{_GDINO}/groundingdino_swint_ogc.pth",
        size_mb=694,
        notes=(
            "Open-vocabulary object detection. Use with SAM for text-prompted segmentation. "
            "Config: GroundingDINO_SwinT_OGC.py"
        ),
    ),
    CatalogEntry(
        key="gdino-swinb",
        title="GroundingDINO Swin-B (text-guided seg)",
        category="sam",
        source="direct",
        url=f"{_GDINO}/groundingdino_swinb_cogcoor.pth",
        size_mb=938,
        notes=(
            "Larger GroundingDINO — higher accuracy, slower. "
            "Config: GroundingDINO_SwinB_cfg.py"
        ),
    ),

    # ── Upscalers ────────────────────────────────────────────────────────────
    CatalogEntry(
        key="up-realesrgan-x4",
        title="RealESRGAN 4x+",
        category="upscaler",
        source="direct",
        url="https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth",
        size_mb=64,
        notes="General-purpose 4x upscaler. Good for photos.",
    ),
    CatalogEntry(
        key="up-realesrgan-anime",
        title="RealESRGAN 4x+ Anime6B",
        category="upscaler",
        source="direct",
        url="https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth",
        size_mb=18,
        notes="Anime/illustration 4x upscaler. Tiny model.",
    ),
    CatalogEntry(
        key="up-realesrgan-x2",
        title="RealESRGAN 2x+",
        category="upscaler",
        source="direct",
        url="https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth",
        size_mb=64,
    ),
    CatalogEntry(
        key="up-4x-ultrasharp",
        title="4x-UltraSharp (ESRGAN)",
        category="upscaler",
        source="direct",
        url="https://huggingface.co/lokCX/4x-Ultrasharp/resolve/main/4x-UltraSharp.pth",
        size_mb=64,
        notes="Very popular community upscaler — sharper than RealESRGAN for illustrations.",
    ),
    CatalogEntry(
        key="up-4x-foolhardy",
        title="4x_foolhardy_Remacri (ESRGAN)",
        category="upscaler",
        source="direct",
        url="https://huggingface.co/FacehuggerSP/foolhardy_Remacri/resolve/main/4x_foolhardy_Remacri.pth",
        size_mb=64,
        notes="Smooth, natural-looking upscaler — great for faces and textures.",
    ),

    # ── RIFE (frame interpolation) ────────────────────────────────────────────
    CatalogEntry(
        key="rife-47",
        title="RIFE 4.7",
        category="rife",
        source="direct",
        url="https://github.com/hzwer/Practical-RIFE/releases/download/model4.7/rife47.pth",
        size_mb=130,
        notes="Best quality/speed balance. Recommended default.",
    ),
    CatalogEntry(
        key="rife-49",
        title="RIFE 4.9",
        category="rife",
        source="direct",
        url="https://github.com/hzwer/Practical-RIFE/releases/download/model4.9/rife49.pth",
        size_mb=130,
        notes="Latest stable RIFE.",
    ),

    # ── Face swap ─────────────────────────────────────────────────────────────
    CatalogEntry(
        key="fs-inswapper-fp16",
        title="inswapper_128 fp16 (ReActor)",
        category="faceswap",
        source="direct",
        url="https://huggingface.co/datasets/Gourieff/ReActor/resolve/main/models/inswapper_128_fp16.onnx",
        size_mb=264,
        notes="Half-size fp16 build — recommended.",
    ),
    CatalogEntry(
        key="fs-inswapper",
        title="inswapper_128 (ReActor, full)",
        category="faceswap",
        source="direct",
        url="https://huggingface.co/datasets/Gourieff/ReActor/resolve/main/models/inswapper_128.onnx",
        size_mb=529,
    ),
]
